# Generated by Django 2.1.3 on 2019-03-21 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190321_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='schedule',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='app.Schedule'),
            preserve_default=False,
        ),
    ]
