# Generated by Django 2.1.3 on 2019-03-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_assignedtask_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
