# Generated by Django 2.1.3 on 2019-03-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190321_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='EndTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='EmpNum',
            new_name='required_number_of_employees',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='StartTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='TaskName',
            new_name='task_name',
        ),
    ]
