# Generated by Django 2.1.3 on 2019-03-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190321_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='Day',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='AvailabilityEndTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='AvailabilityStartTime',
            new_name='start_time',
        ),
    ]
