# Generated by Django 2.1.3 on 2019-03-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190321_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_day',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='start_day',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=-1),
            preserve_default=False,
        ),
    ]
