# Generated by Django 2.1.3 on 2019-03-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('app', '0008_auto_20190321_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_group',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
    ]
