# Generated by Django 2.1.3 on 2019-03-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_task_required_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pay_grade',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
