# Generated by Django 2.1.3 on 2019-03-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile_pay_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='CertType',
            new_name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='app.Location'),
            preserve_default=False,
        ),
    ]
