# Generated by Django 2.1.3 on 2019-03-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190326_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='reason_denied',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='reason_requested',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
