# Generated by Django 2.1.3 on 2019-03-26 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190326_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(blank=True, default='22:00'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(blank=True, default='6:00'),
        ),
    ]
