# Generated by Django 2.1.3 on 2019-03-26 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190326_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Location'),
        ),
    ]
