# Generated by Django 2.1.3 on 2019-04-02 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190402_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='template',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='app.Template'),
            preserve_default=False,
        ),
    ]
