# Generated by Django 2.1.3 on 2019-04-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190402_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_hours_per_day',
            field=models.IntegerField(default=10),
        ),
    ]
