# Generated by Django 2.1.3 on 2019-04-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190402_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_hours_per_week',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_hours_per_day',
            field=models.IntegerField(),
        ),
    ]
