# Generated by Django 2.1.3 on 2019-04-03 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190402_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avoid_overtime', models.BooleanField()),
                ('start_overtime_at', models.IntegerField()),
                ('take_preferernces_into_account', models.BooleanField()),
                ('allow_split_shifts', models.BooleanField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Template')),
            ],
        ),
    ]
