# Generated by Django 2.1.3 on 2019-04-03 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_optimizationsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizationsettings',
            name='template',
        ),
        migrations.AddField(
            model_name='template',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.OptimizationSettings'),
        ),
    ]
