# Generated by Django 2.1.3 on 2019-04-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20190403_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='number_of_employees_needed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
