# Generated by Django 2.1.7 on 2019-04-22 01:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0029_auto_20190418_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Notification Title', max_length=30)),
                ('message', models.TextField(blank=True, default='Notification Message')),
                ('time_sent', models.DateTimeField(default=datetime.datetime(2019, 4, 21, 20, 35, 3, 870513))),
                ('is_selected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.CharField(default='Task Description', max_length=140),
        ),
    ]
