## Generated by Django 2.1.3 on 2019-04-21 18:08

from django.db import migrations


#class Migration(migrations.Migration):

#    dependencies = [
#        ('app', '0029_auto_20190418_0855'),
#    ]

#    operations = [
#        migrations.RenameField(
#            model_name='task',
#            old_name='requried_number_of_employees',
#            new_name='required_number_of_employees',
#        ),
#    ]

class Migration(migrations.Migration):
    dependencies = []
    operations = []
