# Generated by Django 2.1.7 on 2019-04-23 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20190421_2035'),
        ('app', '0030_auto_20190421_1308'),
    ]

    operations = [
    ]
