# Generated by Django 2.1.3 on 2019-04-24 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_merge_20190422_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 19, 43, 6, 737384)),
        ),
    ]
