# Generated by Django 2.1.7 on 2019-04-25 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20190425_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 5, 3, 4, 138267)),
        ),
    ]
