# Generated by Django 2.1.7 on 2019-04-25 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20190425_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 5, 6, 50, 451812)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification Title', max_length=255),
        ),
    ]
