# Generated by Django 2.1.3 on 2019-04-30 14:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20190425_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedrole',
            name='user',
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='user',
        ),
        migrations.AddField(
            model_name='assignedrole',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 9, 25, 55, 286986)),
        ),
    ]
